name = "gleamstrom"
version = "0.1.0"


description = "Implementation of the Maelstrom protocol"
licences = ["Apache-2.0"]
repository = { type = "github", user = "PieterJanVdb", repo = "gleamstrom" }
target = "erlang"


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
